name: Build on tag

on:
  push:
    tags:
      - test-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build docker image
        env:
          DRIVER_DOWNLOADS_ACCESS_KEY_ID: ${{ secrets.DRIVER_DOWNLOADS_ACCESS_KEY_ID }}
          DRIVER_DOWNLOADS_SECRET_ACCESS_KEY: ${{ secrets.DRIVER_DOWNLOADS_SECRET_ACCESS_KEY }}
        run: |
          docker compose build tests
          docker network create connection_api-tests
          docker compose run --rm tests php -v
          docker compose run --rm tests composer ci
      -
        name: List images
        run: docker images
      -
        name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      -
        name: Tag and push to quay.io
        run: |
          TAG="${GITHUB_REF##*/}"
          docker tag keboola/storage-api-tests quay.io/keboola/storage-api-tests:$TAG
          docker push quay.io/keboola/storage-api-tests:$TAG
